name: CI

on: [pull_request]
  
env:
  BUNDLE_PATH: vendor/bundle
  DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  android:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Build and Test SDK
        run: |
          cd android
          bash ./gradlew airship-framework-proxy:assembleDebug airship-framework-proxy:testDebugUnitTest --info --stacktrace
          cd -
        
      - name: publish unit test reports
        if: always()
        uses: mikepenz/action-junit-report@a6502270b81b22b7cf745720fcf00edf7d31dc04
        with:
          check_name: 'Unit test reports'
          github_token: ${{ github.token }}
          report_paths: '**/build/test-results/**/TEST-*.xml'
          fail_on_failure: true
          
  ios:
    runs-on: macOS-12
    steps:
      - name: Set env variable
        run: echo "ImageVersion=$ImageVersion"  >> $GITHUB_ENV
        
      - uses: actions/checkout@v2
      
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ env.ImageVersion }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-${{ env.ImageVersion }}
          
      - name: Install Coreutils
        run: brew install coreutils

      - name: Build SDK
        run: |
          cd ios
          pod install
          xcodebuild -scheme AirshipFrameworkProxy build
          cd -
        
      - name: Pod lint
        run: |
          cd ios
          exec pod lib lint AirshipFrameworkProxy.podspec --verbose --platforms=ios --fail-fast --skip-tests
          cd -
